# Open OnDemand Configuration
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# The SLATE instance value.
Instance: "global"

replicaCount: 1

setupKeycloak: false

SLATE:
  Cluster:
    DNSName: "utah-dev.slateci.net"
