apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "open-ondemand.fullname" . }}
  labels:
    {{- include "open-ondemand.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "open-ondemand.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "open-ondemand.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "open-ondemand.serviceAccountName" . }}
      containers:
        - name: open-ondemand 
          image: jstidd/open-ondemand
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
        - name: keycloak
          image: jstidd/keycloak
          imagePullPolicy: Always
          ports:
            - name: kc
              containerPort: 8443
              protocol: TCP

              
