apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "open-ondemand.fullname" . }}-island
  labels:
    {{- include "open-ondemand.labels" . | nindent 4 }}-island
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "open-ondemand.selectorLabels" . | nindent 6 }}-island
  template:
    metadata:
      labels:
        {{- include "open-ondemand.selectorLabels" . | nindent 8 }}-island
    spec:
      serviceAccountName: {{ include "open-ondemand.serviceAccountName" . }}
      volumes:
        - name: shared-data
          emptyDir: {}
      containers:
        - name: ood-island
          image: dockerbox88/open-ondemand-island
          imagePullPolicy: Always
          volumeMounts:
            - name: shared-data
              mountPath: /shared
          ports:
            - name: ssh
              containerPort: 22
              protocol: TCP