apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "open-ondemand.fullname" . }}
  labels:
    {{- include "open-ondemand.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "open-ondemand.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "open-ondemand.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "open-ondemand.serviceAccountName" . }}
      volumes:
        - name: shared-data
          emptyDir: {}
      containers:
        - name: open-ondemand
          image: dockerbox88/open-ondemand
          imagePullPolicy: Always
          volumeMounts:
            - name: shared-data
              mountPath: /shared
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          env:
            - name: INSTANCE_NAME
              value: {{ include "open-ondemand.fullname" . }}
        - name: keycloak
          image: jstidd/keycloak
          imagePullPolicy: Always
          volumeMounts:
            - name: shared-data
              mountPath: /shared
          ports:
            - name: kc8080
              containerPort: 8080
              protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "open-ondemand.fullname" . }}-island
  labels:
    {{- include "open-ondemand.labels" . | nindent 4 }}-island
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "open-ondemand.selectorLabels" . | nindent 6 }}-island
  template:
    metadata:
      labels:
        {{- include "open-ondemand.selectorLabels" . | nindent 8 }}-island
    spec:
      serviceAccountName: {{ include "open-ondemand.serviceAccountName" . }}
      volumes:
        - name: shared-data
          emptyDir: {}
      containers:
        - name: ood-island
          image: dockerbox88/open-ondemand-island
          imagePullPolicy: Always
          volumeMounts:
            - name: shared-data
              mountPath: /shared
          ports:
            - name: ssh
              containerPort: 22
              protocol: TCP
          env:
            - name: INSTANCE_NAME
              value: {{ include "open-ondemand.fullname" . }}
---