apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "open-ondemand.fullname" . }}-shell-setup
data:
  clusters.yaml: |
    ---
    v2:
      metadata:
        title: "{{ .Values.cluster1.name }}"
        priority: 2
      login:
        host: "{{ .Values.cluster1.host }}"
      job:
        adapter: "linux_host"
        submit_host: "{{ .Values.cluster1.name }}"
        ssh_hosts:
          - node1.slateci.net
          - node2.slateci.net
        site_timeout: 7200
        debug: true
        singularity_bin: /path/to/your/singularity
        singularity_bindpath: /etc,/media,/mnt,/opt,/run,/srv,/usr,/var,/users
        singularity_image: /path/to/your/image.sif  # Something like centos_7.6.sif
        # If strict_host_checking is enabled then any unlisted nodes may cause adapter to fail round-robin
        strict_host_checking: false
        tmux_bin: /path/to/your/tmux
      batch_connect:
        basic:
          script_wrapper: |
            #!/bin/bash
            ###### your_script_here ######
        vnc:
          script_wrapper: |
            #!/bin/bash
            ###### your_vnc_startup_here ######