apiVersion: v1
kind: ConfigMap
data:
  clusters.yaml: |
    ---
    v2:
      metadata:
        title: "{{ .Values.cluster1.name }}"
        priority: 2
      login:
        host: "{{ .Values.cluster1.host }}"
metadata:
  name: {{ include "open-ondemand.fullname" . }}-shell-setup
