---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ include "open-ondemand.fullname" . }}-island
  labels:
    {{- include "open-ondemand.labels" . | nindent 4 }}-island
  annotations:
    kubernetes.io/ingress.class: slate
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - ood-island.{{ .Values.SLATE.Cluster.DNSName}}
    secretName: {{ .Values.Instance}}-open-ondemand-ood-island
  rules:
  - host: ood-island.{{ .Values.SLATE.Cluster.DNSName}}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ include "open-ondemand.fullname" . }}-ood-island
          servicePort: 22
---