{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "open-ondemand.serviceAccountName" . }}
  labels:
{{ include "open-ondemand.labels" . | nindent 4 }}
{{- end -}}
