apiVersion: v1
kind: Service
metadata:
  name: {{ include "open-ondemand.fullname" . }}
  labels:
    {{- include "open-ondemand.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 
      protocol: TCP
      name: http
  selector:
    {{- include "open-ondemand.selectorLabels" . | nindent 4 }}
