apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "open-ondemand.fullname" . }}-sssd-conf
data:
  sssd.conf: |
    [sssd]
    config_file_version = 2
    reconnection_retries = 3
    sbus_timeout = 30
    services = nss, pam
    domains = {{ .Values.kerberos.realm }}
    [nss]
    filter_groups = root
    filter_users = root
    reconnection_retries = 3
    [pam]
    reconnection_retries = 3
    [domain/{{ .Values.kerberos.realm }}]
    debug_level = 3
    enumerate = false
    id_provider = ldap
    auth_provider = krb5
    access_provider = ldap
    chpass_provider = krb5
    ldap_uri = {{ .Values.ldap.connectionURL }}
    ldap_search_base = {{ .Values.ldap.usersDN }}
    ldap_tls_cacert = /etc/pki/tls/certs/ca-bundle.crt
    ldap_tls_reqcert = never
    krb5_realm = {{ .Values.kerberos.realm }}
    krb5_server = {{ .Values.kerberos.serverPrincipal }}
    krb5_ccname_template = KEYRING:persistent:%U
    krb5_auth_timeout = 15
    krb5_store_password_if_offline = true
    # not needed on clients only LDAP server ldap_krb5_keytab = {{ .Values.kerberos.keyTab }}
    ldap_krb5_init_creds = true
    ldap_krb5_ticket_lifetime = 86400
    cache_credentials = true
    use_fully_qualified_names = false
    ldap_access_filter = {{ .Values.ldap.uuidLDAPAttribute }}=*
    ldap_schema = rfc2307bis
    ldap_group_member = uniqueMember
    override_homedir = /home/%u
    fallback_homedir = /home/%u
    default_shell = /bin/bash
    # Some type of LDAP access filter is required, it is possible to restrict by group